/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * PyInv API
 * Open Source Asset and Quartermaster System
 * OpenAPI spec version: 0.2.0-dev
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export type NodesListNodeType = typeof NodesListNodeType[keyof typeof NodesListNodeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodesListNodeType = {
  A: 'A',
  L: 'L',
} as const;

export type NodesListParams = {
depth?: number;
/**
 * Descendent of
 */
descendent_of?: string;
/**
 * Is Container
 */
is_container?: boolean;
/**
 * Number of results to return per page.
 */
limit?: number;
name?: string;
node_type?: NodesListNodeType;
numchild?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * Parent
 */
parent?: string;
/**
 * A search term.
 */
search?: string;
};

export type ManufacturersListParams = {
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A search term.
 */
search?: string;
};

export type ChangesetsListParams = {
/**
 * Number of Events
 */
event_count_max?: number;
/**
 * Number of Events
 */
event_count_min?: number;
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A search term.
 */
search?: string;
timestamp_after?: string;
timestamp_before?: string;
/**
 * User
 */
user?: number;
};

export type AssetsListParams = {
/**
 * Asset Code
 */
asset_code?: string;
/**
 * Asset Model
 */
asset_model?: string;
created_at_after?: string;
created_at_before?: string;
/**
 * Has Node
 */
has_node?: boolean;
/**
 * Is Container
 */
is_container?: boolean;
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A search term.
 */
search?: string;
updated_at_after?: string;
updated_at_before?: string;
};

export type AssetModelsListParams = {
created_at_after?: string;
created_at_before?: string;
is_container?: boolean;
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * Manufacturer
 */
manufacturer?: string;
/**
 * The initial index from which to return the results.
 */
offset?: number;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A search term.
 */
search?: string;
updated_at_after?: string;
updated_at_before?: string;
};

export type AssetEventsListEventTypeItem = typeof AssetEventsListEventTypeItem[keyof typeof AssetEventsListEventTypeItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetEventsListEventTypeItem = {
  CR: 'CR',
  MV: 'MV',
} as const;

export type AssetEventsListParams = {
/**
 * Asset
 */
asset?: string;
/**
 * ChangeSet
 */
changeset?: string;
event_type?: AssetEventsListEventTypeItem[];
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A search term.
 */
search?: string;
timestamp_after?: string;
timestamp_before?: string;
/**
 * User
 */
user?: number;
};

export interface UserLink {
  readonly username: string;
  readonly display_name: string;
}

export interface TokenVerify {
  token: string;
}

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}

export interface TokenObtainPair {
  username: string;
  password: string;
  readonly access: string;
  readonly refresh: string;
}

/**
 * Serializer for nodes.
 */
export interface PatchedNode {
  readonly id?: string;
  readonly display_name?: string;
  readonly node_type?: NodeTypeEnum;
  readonly numchild?: number;
  readonly is_container?: boolean;
  name?: string;
  readonly asset?: Asset;
  readonly depth?: number;
  readonly ancestors?: NodeLink[];
}

/**
 * Serializer with all information we have about a manufacturer.
 */
export interface PatchedManufacturer {
  name?: string;
  slug?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
}

/**
 * Serializer for AssetModel objects.
 */
export interface PatchedAssetModel {
  name?: string;
  slug?: string | null;
  readonly display_name?: string;
  readonly manufacturer?: ManufacturerLink;
  manufacturer_slug?: string;
  is_container?: boolean;
  readonly asset_count?: number;
  readonly created_at?: string;
  readonly updated_at?: string;
}

export interface PaginatedNodeList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: Node[];
}

export interface PaginatedManufacturerList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: Manufacturer[];
}

export interface PaginatedAssetWithNodeList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: AssetWithNode[];
}

export interface PaginatedAssetModelList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: AssetModel[];
}

export interface PaginatedAssetEventWithAssetList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: AssetEventWithAsset[];
}

export type NodeTypeEnum = typeof NodeTypeEnum[keyof typeof NodeTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NodeTypeEnum = {
  A: 'A',
  L: 'L',
} as const;

/**
 * Serializer with enough information to link to a node.
 */
export interface NodeLink {
  readonly id: string;
  readonly display_name: string;
  readonly node_type: NodeTypeEnum;
  readonly numchild: number;
  readonly is_container: boolean;
}

/**
 * Serializer with enough information to link to a node.
 */
export interface NodeLinkWithParent {
  readonly id: string;
  readonly display_name: string;
  readonly node_type: NodeTypeEnum;
  readonly numchild: number;
  readonly is_container: boolean;
  readonly parent: NodeLink;
}

/**
 * Serializer for nodes.
 */
export interface Node {
  readonly id: string;
  readonly display_name: string;
  readonly node_type: NodeTypeEnum;
  readonly numchild: number;
  readonly is_container: boolean;
  name: string;
  readonly asset: Asset;
  readonly depth: number;
  readonly ancestors: NodeLink[];
}

/**
 * Serializer with enough information to display a link to a manufacturer.
 */
export interface ManufacturerLink {
  name: string;
  slug?: string | null;
}

/**
 * Serializer with all information we have about a manufacturer.
 */
export interface Manufacturer {
  name: string;
  slug?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
}

export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventTypeEnum = {
  CR: 'CR',
  MV: 'MV',
} as const;

export interface ChangeSetSerializerWithCount {
  readonly id: string;
  readonly timestamp: string;
  readonly display_name: string;
  readonly user: UserLink;
  readonly comment: string;
  readonly event_count: number;
}

export interface PaginatedChangeSetSerializerWithCountList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: ChangeSetSerializerWithCount[];
}

export interface ChangeSet {
  readonly id: string;
  readonly timestamp: string;
  readonly display_name: string;
  readonly user: UserLink;
  readonly comment: string;
}

export type AssetWithNodeExtraData = {[key: string]: unknown};

/**
 * Serializer with enough information to link to an asset model.
 */
export interface AssetModelLink {
  name: string;
  slug?: string | null;
}

/**
 * Serializer for Asset objects.
 */
export interface AssetWithNode {
  readonly id: string;
  readonly display_name: string;
  readonly asset_model: AssetModelLink;
  asset_codes: string[];
  readonly first_asset_code: string;
  readonly created_at: string;
  readonly updated_at: string;
  extra_data?: AssetWithNodeExtraData;
  readonly node: NodeLinkWithParent;
}

/**
 * Serializer for AssetModel objects.
 */
export interface AssetModel {
  name: string;
  slug?: string | null;
  readonly display_name: string;
  readonly manufacturer: ManufacturerLink;
  manufacturer_slug: string;
  is_container?: boolean;
  readonly asset_count: number;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface AssetLink {
  readonly id: string;
  readonly display_name: string;
}

export type AssetEventWithAssetEventData = {[key: string]: unknown};

export interface AssetEventWithAsset {
  readonly id: string;
  readonly changeset: ChangeSet;
  readonly event_type: EventTypeEnum;
  readonly asset: AssetLink;
  readonly event_data: AssetEventWithAssetEventData;
}

export type AssetExtraData = {[key: string]: unknown};

/**
 * Serializer for Asset objects.
 */
export interface Asset {
  readonly id: string;
  readonly display_name: string;
  readonly asset_model: AssetModelLink;
  asset_codes: string[];
  readonly first_asset_code: string;
  readonly created_at: string;
  readonly updated_at: string;
  extra_data?: AssetExtraData;
}





  /**
 * Fetch or update the profile of the current user.
 */
export const accountsProfileRetrieve = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/accounts/profile/`,options
    );
  }

/**
 * Fetch or update the profile of the current user.
 */
export const accountsProfileUpdate = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/accounts/profile/`,undefined,options
    );
  }

/**
 * Fetch or update the profile of the current user.
 */
export const accountsProfilePartialUpdate = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/accounts/profile/`,undefined,options
    );
  }

/**
 * Fetch information about asset events.
 */
export const assetEventsList = <TData = AxiosResponse<PaginatedAssetEventWithAssetList>>(
    params?: AssetEventsListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/asset-events/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch information about asset events.
 */
export const assetEventsRetrieve = <TData = AxiosResponse<AssetEventWithAsset>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/asset-events/${id}/`,options
    );
  }

/**
 * Fetch information about asset models.
 */
export const assetModelsList = <TData = AxiosResponse<PaginatedAssetModelList>>(
    params?: AssetModelsListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/asset-models/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch information about asset models.
 */
export const assetModelsCreate = <TData = AxiosResponse<AssetModel>>(
    assetModel: NonReadonly<AssetModel>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/asset-models/`,
      assetModel,options
    );
  }

/**
 * Fetch information about asset models.
 */
export const assetModelsRetrieve = <TData = AxiosResponse<AssetModel>>(
    slug: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/asset-models/${slug}/`,options
    );
  }

/**
 * Fetch information about asset models.
 */
export const assetModelsUpdate = <TData = AxiosResponse<AssetModel>>(
    slug: string,
    assetModel: NonReadonly<AssetModel>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/asset-models/${slug}/`,
      assetModel,options
    );
  }

/**
 * Fetch information about asset models.
 */
export const assetModelsPartialUpdate = <TData = AxiosResponse<AssetModel>>(
    slug: string,
    patchedAssetModel: NonReadonly<PatchedAssetModel>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/asset-models/${slug}/`,
      patchedAssetModel,options
    );
  }

/**
 * Fetch information about asset models.
 */
export const assetModelsDestroy = <TData = AxiosResponse<void>>(
    slug: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/asset-models/${slug}/`,options
    );
  }

/**
 * Fetch information about assets.
 */
export const assetsList = <TData = AxiosResponse<PaginatedAssetWithNodeList>>(
    params?: AssetsListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/assets/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch information about assets.
 */
export const assetsRetrieve = <TData = AxiosResponse<AssetWithNode>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/assets/${id}/`,options
    );
  }

/**
 * Takes a set of user credentials and returns an access and refresh JSON web
token pair to prove the authentication of those credentials.
 */
export const authTokenCreate = <TData = AxiosResponse<TokenObtainPair>>(
    tokenObtainPair: NonReadonly<TokenObtainPair>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/token/`,
      tokenObtainPair,options
    );
  }

/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authTokenRefreshCreate = <TData = AxiosResponse<TokenRefresh>>(
    tokenRefresh: NonReadonly<TokenRefresh>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/token/refresh/`,
      tokenRefresh,options
    );
  }

/**
 * Takes a token and indicates if it is valid.  This view provides no
information about a token's fitness for a particular use.
 */
export const authTokenVerifyCreate = <TData = AxiosResponse<TokenVerify>>(
    tokenVerify: TokenVerify, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/token/verify/`,
      tokenVerify,options
    );
  }

/**
 * Fetch information about asset events.
 */
export const changesetsList = <TData = AxiosResponse<PaginatedChangeSetSerializerWithCountList>>(
    params?: ChangesetsListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/changesets/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch information about asset events.
 */
export const changesetsRetrieve = <TData = AxiosResponse<ChangeSetSerializerWithCount>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/changesets/${id}/`,options
    );
  }

/**
 * Get the events in the changeset.
 */
export const changesetsEventsRetrieve = <TData = AxiosResponse<ChangeSetSerializerWithCount>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/changesets/${id}/events/`,options
    );
  }

/**
 * Fetch information about manufacturers.
 */
export const manufacturersList = <TData = AxiosResponse<PaginatedManufacturerList>>(
    params?: ManufacturersListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/manufacturers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch information about manufacturers.
 */
export const manufacturersCreate = <TData = AxiosResponse<Manufacturer>>(
    manufacturer: NonReadonly<Manufacturer>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/manufacturers/`,
      manufacturer,options
    );
  }

/**
 * Fetch information about manufacturers.
 */
export const manufacturersRetrieve = <TData = AxiosResponse<Manufacturer>>(
    slug: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/manufacturers/${slug}/`,options
    );
  }

/**
 * Fetch information about manufacturers.
 */
export const manufacturersUpdate = <TData = AxiosResponse<Manufacturer>>(
    slug: string,
    manufacturer: NonReadonly<Manufacturer>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/manufacturers/${slug}/`,
      manufacturer,options
    );
  }

/**
 * Fetch information about manufacturers.
 */
export const manufacturersPartialUpdate = <TData = AxiosResponse<Manufacturer>>(
    slug: string,
    patchedManufacturer: NonReadonly<PatchedManufacturer>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/manufacturers/${slug}/`,
      patchedManufacturer,options
    );
  }

/**
 * Fetch information about manufacturers.
 */
export const manufacturersDestroy = <TData = AxiosResponse<void>>(
    slug: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/manufacturers/${slug}/`,options
    );
  }

/**
 * Fetch information about nodes.
 */
export const nodesList = <TData = AxiosResponse<PaginatedNodeList>>(
    params?: NodesListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/nodes/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch information about nodes.
 */
export const nodesRetrieve = <TData = AxiosResponse<Node>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/nodes/${id}/`,options
    );
  }

/**
 * Fetch information about nodes.
 */
export const nodesUpdate = <TData = AxiosResponse<Node>>(
    id: string,
    node: NonReadonly<Node>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/nodes/${id}/`,
      node,options
    );
  }

/**
 * Fetch information about nodes.
 */
export const nodesPartialUpdate = <TData = AxiosResponse<Node>>(
    id: string,
    patchedNode: NonReadonly<PatchedNode>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/nodes/${id}/`,
      patchedNode,options
    );
  }

export type AccountsProfileRetrieveResult = AxiosResponse<void>
export type AccountsProfileUpdateResult = AxiosResponse<void>
export type AccountsProfilePartialUpdateResult = AxiosResponse<void>
export type AssetEventsListResult = AxiosResponse<PaginatedAssetEventWithAssetList>
export type AssetEventsRetrieveResult = AxiosResponse<AssetEventWithAsset>
export type AssetModelsListResult = AxiosResponse<PaginatedAssetModelList>
export type AssetModelsCreateResult = AxiosResponse<AssetModel>
export type AssetModelsRetrieveResult = AxiosResponse<AssetModel>
export type AssetModelsUpdateResult = AxiosResponse<AssetModel>
export type AssetModelsPartialUpdateResult = AxiosResponse<AssetModel>
export type AssetModelsDestroyResult = AxiosResponse<void>
export type AssetsListResult = AxiosResponse<PaginatedAssetWithNodeList>
export type AssetsRetrieveResult = AxiosResponse<AssetWithNode>
export type AuthTokenCreateResult = AxiosResponse<TokenObtainPair>
export type AuthTokenRefreshCreateResult = AxiosResponse<TokenRefresh>
export type AuthTokenVerifyCreateResult = AxiosResponse<TokenVerify>
export type ChangesetsListResult = AxiosResponse<PaginatedChangeSetSerializerWithCountList>
export type ChangesetsRetrieveResult = AxiosResponse<ChangeSetSerializerWithCount>
export type ChangesetsEventsRetrieveResult = AxiosResponse<ChangeSetSerializerWithCount>
export type ManufacturersListResult = AxiosResponse<PaginatedManufacturerList>
export type ManufacturersCreateResult = AxiosResponse<Manufacturer>
export type ManufacturersRetrieveResult = AxiosResponse<Manufacturer>
export type ManufacturersUpdateResult = AxiosResponse<Manufacturer>
export type ManufacturersPartialUpdateResult = AxiosResponse<Manufacturer>
export type ManufacturersDestroyResult = AxiosResponse<void>
export type NodesListResult = AxiosResponse<PaginatedNodeList>
export type NodesRetrieveResult = AxiosResponse<Node>
export type NodesUpdateResult = AxiosResponse<Node>
export type NodesPartialUpdateResult = AxiosResponse<Node>
